server:
  port: 8082

spring:
  application:
    name: nursing-catalog-service
  config:
    import: ${NURSING_NACOS_CONFIG_PREFIX:}nacos:${spring.application.name}-${spring.profiles.active:dev}.yaml?group=NURSING&refreshEnabled=true
  datasource:
    url: ${NURSING_CATALOG_DB_URL}
    username: ${NURSING_DB_USERNAME}
    password: ${NURSING_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      config:
        server-addr: ${NURSING_NACOS_ADDR}
        namespace: ${NURSING_NACOS_NAMESPACE:}
        username: ${NURSING_NACOS_USERNAME:}
        password: ${NURSING_NACOS_PASSWORD:}
      discovery:
        server-addr: ${NURSING_NACOS_ADDR}
        namespace: ${NURSING_NACOS_NAMESPACE:}
        group: NURSING

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.nursing.catalog.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
