spring:
  application:
    name: nursing-order-service
  profiles:
    default: dev
  config:
    import:
      - nacos:${spring.application.name}.yaml?group=NURSING&refreshEnabled=false
      - nacos:${spring.application.name}-${spring.profiles.active:dev}.yaml?group=NURSING&refreshEnabled=false
  cloud:
    nacos:
      config:
        server-addr: ${NURSING_NACOS_ADDR}
        namespace: ${NURSING_NACOS_NAMESPACE:}
        username: ${NURSING_NACOS_USERNAME:}
        password: ${NURSING_NACOS_PASSWORD:}
      discovery:
        server-addr: ${NURSING_NACOS_ADDR}
        namespace: ${NURSING_NACOS_NAMESPACE:}
        group: NURSING

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      force-response: true
